com.identidock:
  build: .
  ports:
    - "5000:5000"
  environment:
    ENV: DEV
  volumes:
    - ./app:/app
  links:
    - com.identidock.dnmonster
    - com.identidock.redis


com.identidock.dnmonster:
  image: amouat/dnmonster:1.0


com.identidock.redis:
  image: redis:3.0
    

